# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  
  pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git'
  pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git'
  pod 'FBSDKShareKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git'
  

  # Pods for app

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'

  end

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app-tvOS

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
